name: Terraform CI/CD (Stage)

on:
  workflow_call:
    inputs:
      image_url:
        required: true
        type: string
      target_branch:
        required: true
        type: string
      destroy:
        required: false
        type: boolean
        default: false

  workflow_dispatch:
    inputs:
      image_url:
        description: 'Docker image URL'
        required: true
        type: string
      target_branch:
        description: 'Terraform code branch to deploy'
        required: true
        type: string
      destroy:
        description: 'Manually confirm to destroy resources'
        required: false
        type: boolean
        default: false

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: Terraform Deploy - Stage
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ap-south-1

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout Terraform Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.target_branch || inputs.target_branch }}

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::851725602228:role/GitHubTerraform-role
          role-session-name: github-actions
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Get Latest ECS Optimized AMI ID
        id: get-ami
        run: |
          ECS_AMI_ID=$(aws ssm get-parameters \
            --names /aws/service/ecs/optimized-ami/amazon-linux-2/recommended/image_id \
            --region $AWS_REGION \
            --query "Parameters[0].Value" \
            --output text)
          echo "ECS_AMI_ID=${ECS_AMI_ID}" >> $GITHUB_ENV

      - name: Terraform Init
        run: terraform -chdir=stage-environment init -backend-config="key=stage/terraform.tfstate"

      - name: Terraform Validate
        run: terraform -chdir=stage-environment validate

      - name: Terraform Plan
        if: ${{ !(github.event.inputs.destroy == 'true' || inputs.destroy == true) }}
        run: |
          terraform -chdir=stage-environment plan \
            -var="image_url=${{ github.event.inputs.image_url || inputs.image_url }}" \
            -var="ecs_ami_id=${{ env.ECS_AMI_ID }}"

      - name: Terraform Apply
        if: ${{ !(github.event.inputs.destroy == 'true' || inputs.destroy == true) }}
        run: |
          terraform -chdir=stage-environment apply -auto-approve \
            -var="image_url=${{ github.event.inputs.image_url || inputs.image_url }}" \
            -var="ecs_ami_id=${{ env.ECS_AMI_ID }}"

      - name: Terraform Destroy
        if: ${{ github.event.inputs.destroy == 'true' || inputs.destroy == true }}
        run: |
          echo "Destroy confirmed. Proceeding..."
          terraform -chdir=stage-environment destroy -auto-approve \
            -var="image_url=${{ github.event.inputs.image_url || inputs.image_url }}" \
            -var="ecs_ami_id=${{ env.ECS_AMI_ID }}"
