name: Terraform CI/CD (Stage)

on:
  workflow_call:
    inputs:
      image_url:
        required: true
        type: string
      target_branch:
        required: true
        type: string
      destroy:
        required: false
        type: boolean
        default: false

jobs:
  terraform-apply:
    name: Terraform Apply (Stage)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Terraform Code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

  terraform-destroy:
    name: Terraform Destroy (If Requested)
    needs: terraform-apply
    if: ${{ inputs.destroy == true }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Terraform Code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy Plan
        run: terraform plan -destroy -out=tfplans

      - name: Terraform Destroy Apply
        run: terraform apply -auto-approve tfplan
