name: Terraform Infra Only

on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: 'Git branch to use (dev, stage, main)'
        required: true
        type: string
      env_name:
        description: 'Environment name (dev, stage, prod)'
        required: true
        type: string
      destroy:
        description: 'Set true to destroy infrastructure'
        required: false
        default: false
        type: boolean

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-south-1
  AWS_ACCOUNT_ID: 851725602228

jobs:
  terraform:
    name: ${{ inputs.destroy == 'true' && 'Destroy' || 'Deploy' }} Infra - ${{ inputs.env_name }}
    runs-on: ubuntu-latest

    env:
      ENV_FOLDER: ${{ inputs.env_name }}-environment

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.target_branch }}

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::851725602228:role/Githubterraform-newrole
          role-session-name: terraform-session
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init -backend-config="key=${{ inputs.env_name }}/terraform.tfstate"
        working-directory: ${{ env.ENV_FOLDER }}

      - name: Terraform Format
        run: terraform fmt -check
        working-directory: ${{ env.ENV_FOLDER }}

      - name: Terraform Validate
        run: terraform validate
        working-directory: ${{ env.ENV_FOLDER }}

      - name: Terraform Plan
        run: terraform plan -var-file="terraform.tfvars"
        working-directory: ${{ env.ENV_FOLDER }}

      - name: Terraform Apply
        if: inputs.destroy == 'false'
        run: terraform apply -auto-approve -var-file="terraform.tfvars"
        working-directory: ${{ env.ENV_FOLDER }}

      - name: Terraform Destroy
        if: inputs.destroy == 'true'
        run: terraform destroy -auto-approve -var-file="terraform.tfvars"
        working-directory: ${{ env.ENV_FOLDER }}
